require "csv"

CANT_DJ_Y_ULT_ACT = 1.day # :index, CANTIDAD DE DDJJ Y ULTIMA ACTUALIZACION
TIME_CACHE_FILTROS = 1.day # get_filtros
TIME_CACHE_SEARCH = 1.day # search
TIME_CACHE_VIEW_DDJJ = 1.minutes # get_ddjj
TIME_CACHE_DATA_JSON = 15.day # data_bienes, data_personas
EXPORTAR_DATA = 30.day  ## CANTIDAD DE DIAS QUE HAY ENTRE QUE SE SUBEN LOS DATOS Y SE PUEDAN BAJAR

PERMITIR_EXPORTAR_DATA = true  ## PERMITE O NO EXPORTAR LA DATA
