require "csv"

CANT_DJ_Y_ULT_ACT = 10.minutes # :index, CANTIDAD DE DDJJ Y ULTIMA ACTUALIZACION
TIME_CACHE_FILTROS = 10.minutes # get_filtros
TIME_CACHE_SEARCH = 10.minutes # search
TIME_CACHE_VIEW_DDJJ = 5.minutes # get_ddjj
TIME_CACHE_DATA_JSON = 1.day # data_bienes, data_personas
EXPORTAR_DATA = 1.minutes  ## CANTIDAD DE DIAS QUE HAY ENTRE QUE SE SUBEN LOS DATOS Y SE PUEDAN BAJAR

PERMITIR_EXPORTAR_DATA = true  ## PERMITE O NO EXPORTAR LA DATA
